### ISSUE TITLE
Problem with google/protobuf: quantized version of U2NET is not parsed properly

### ISSUE THREAD

**Issue by gakowalski** [gakowalski/onnx-php#1]
```sh
php info.php u2net.quant.onnx
```

Results in:

> Fatal error: Uncaught Google\Protobuf\Internal\GPBDecodeException: Error occurred during parsing: Unexpected EOF inside bytes field. in F:\laragon\www\onnx-php\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php:442
> Stack trace:
> #0 F:\laragon\www\onnx-php\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php(515): Google\Protobuf\Internal\Message::parseFieldFromStreamNoTag(Object(Google\Protobuf\Internal\CodedInputStream), Object(Google\Protobuf\Internal\FieldDescriptor), NULL)
> #1 F:\laragon\www\onnx-php\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php(811): Google\Protobuf\Internal\Message->parseFieldFromStream(74, Object(Google\Protobuf\Internal\CodedInputStream), Object(Google\Protobuf\Internal\FieldDescriptor))
> #2 F:\laragon\www\onnx-php\vendor\google\protobuf\src\Google\Protobuf\Internal\GPBWire.php(289): Google\Protobuf\Internal\Message->parseFromStream(Object(Google\Protobuf\Internal\CodedInputStream))
> #3 F:\laragon\www\onnx-php\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php(435): Google\Protobuf\Internal\GPBWire::readMessage(Object(Google\Protobuf\Internal\CodedInputStream), Object(Onnx\TensorProto))
> #4 F:\laragon\www\onnx-php\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php(515): Google\Protobuf\Internal\Message::parseFieldFromStreamNoTag(Object(Google\Protobuf\Internal\CodedInputStream), Object(Google\Protobuf\Internal\FieldDescriptor), Object(Onnx\TensorProto))
> #5 F:\laragon\www\onnx-php\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php(811): Google\Protobuf\Internal\Message->parseFieldFromStream(42, Object(Google\Protobuf\Internal\CodedInputStream), Object(Google\Protobuf\Internal\FieldDescriptor))
> #6 F:\laragon\www\onnx-php\vendor\google\protobuf\src\Google\Protobuf\Internal\GPBWire.php(289): Google\Protobuf\Internal\Message->parseFromStream(Object(Google\Protobuf\Internal\CodedInputStream))
> #7 F:\laragon\www\onnx-php\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php(435): Google\Protobuf\Internal\GPBWire::readMessage(Object(Google\Protobuf\Internal\CodedInputStream), Object(Onnx\GraphProto))
> #8 F:\laragon\www\onnx-php\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php(515): Google\Protobuf\Internal\Message::parseFieldFromStreamNoTag(Object(Google\Protobuf\Internal\CodedInputStream), Object(Google\Protobuf\Internal\FieldDescriptor), Object(Onnx\GraphProto))
> #9 F:\laragon\www\onnx-php\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php(811): Google\Protobuf\Internal\Message->parseFieldFromStream(58, Object(Google\Protobuf\Internal\CodedInputStream), Object(Google\Protobuf\Internal\FieldDescriptor))
> #10 F:\laragon\www\onnx-php\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php(775): Google\Protobuf\Internal\Message->parseFromStream(Object(Google\Protobuf\Internal\CodedInputStream))
> #11 F:\laragon\www\onnx-php\info.php(16): Google\Protobuf\Internal\Message->mergeFromString('\x08\x06\x12\ronnx.quanti...')
> #12 {main}
>   thrown in F:\laragon\www\onnx-php\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php on line 442

Found similar error described here:

https://github.com/protocolbuffers/protobuf/issues/3171

**Comment by gakowalski** [comment]
It seems that while reading field `raw_data` of some `Tensor` struct, data length exceeds buffer size. As a consequence, `Google\Protobuf\Internal\CodedInputStream::readRaw($size, $buffer)` returns `false` and this triggers exception in `GPBWire.php`.

**Comment by gakowalski** [comment]
It seems that there is internal hardcoded byte limit called `$total_bytes_limit` defined in `Google\Protobuf\Internal\CodedInputStream`. From Protobuf docs for C++:

> To prevent malicious users from sending excessively large messages and causing memory exhaustion, [CodedInputStream](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.io.coded_stream#CodedInputStream) imposes a hard limit on the total number of bytes it will read.

C++ version of protobuf [has a method to programatically change this limit](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.io.coded_stream#total-bytes-limit) but there is no such function in PHP versioin. ONNX models can be very large in size, so the limit is being reached which in the end throws GPBDecodeException.

**Comment by gakowalski** [comment]
According to docs, default limit for C++ versions is `INT_MAX` - which equals 2 GB. But for PHP version its hardcoded as `32 MB`.

**Comment by gakowalski** [comment]
Submitted the problem to protobuf github issue tracker:
https://github.com/protocolbuffers/protobuf/issues/9990

**Comment by gakowalski** [comment]
Issue solved in referenced commit. Problem is in google/protobuf, issue and pull request were made.
